# Generated by Django 3.1.3 on 2020-12-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infected', models.BooleanField(default=False)),
                ('organism_mnemonic', models.CharField(max_length=80)),
                ('sex', models.CharField(max_length=15)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'organism',
                'managed': True,
                'unique_together': {('infected', 'organism_mnemonic', 'sex', 'description')},
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, max_length=200, null=True)),
                ('subsequence', models.CharField(max_length=4500)),
                ('start_pos', models.IntegerField()),
                ('end_pos', models.IntegerField()),
            ],
            options={
                'db_table': 'pattern',
                'managed': True,
                'unique_together': {('hash', 'start_pos', 'end_pos')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, max_length=200, null=True)),
                ('sequence', models.CharField(max_length=4500)),
                ('organism', models.ForeignKey(db_column='organism', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app.organism')),
            ],
            options={
                'db_table': 'protein',
                'managed': True,
                'unique_together': {('hash', 'organism')},
            },
        ),
        migrations.CreateModel(
            name='ProteinPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_count', models.IntegerField()),
                ('similarity', models.FloatField()),
                ('protein1', models.ForeignKey(db_column='protein1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='protein_1', to='app.protein')),
                ('protein2', models.ForeignKey(db_column='protein2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='protein_2', to='app.protein')),
            ],
            options={
                'db_table': 'protein_pair',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResultSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.ForeignKey(db_column='pattern', on_delete=django.db.models.deletion.DO_NOTHING, to='app.pattern')),
                ('protein_pair', models.ForeignKey(db_column='protein_pair', on_delete=django.db.models.deletion.DO_NOTHING, to='app.proteinpair')),
            ],
            options={
                'db_table': 'result_set',
                'managed': True,
            },
        ),
    ]
